// Signature database for detecting third-party services on a web page.
//
// Each signature can match against several evidence sources collected by the
// analyzer:
//   - url:     regex tested against every network request URL + every <script src>
//   - html:    regex tested against the rendered HTML
//   - global:  name of a property expected on `window` (checked in the page)
//   - cookie:  regex tested against cookie names
//
// `category` groups results in the UI. `competitor: true` flags vendors that
// compete in the search / discovery / personalization space.

/** @typedef {{
 *   id: string,
 *   name: string,
 *   category: string,
 *   competitor?: boolean,
 *   website?: string,
 *   url?: RegExp[],
 *   html?: RegExp[],
 *   global?: string[],
 *   cookie?: RegExp[],
 * }} Signature */

const CAT = {
  SEARCH: "Search & Discovery",
  PERSONALIZATION: "Personalization & Recommendations",
  MERCH: "Merchandising & Experience",
  ANALYTICS: "Analytics & Tags",
  PLATFORM: "Commerce Platform",
};

/** @type {Signature[]} */
const SIGNATURES = [
  // ---------------------------------------------------------------------------
  // Direct competitors: site search / product discovery
  // ---------------------------------------------------------------------------
  {
    id: "algolia",
    name: "Algolia",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://www.algolia.com",
    url: [/algolia\.net/i, /algolianet\.com/i, /algolia\.io/i, /cdn\.jsdelivr\.net\/npm\/(instantsearch|algoliasearch)/i],
    html: [/instantsearch/i, /algoliasearch/i, /data-insights-token/i],
    global: ["algoliasearch", "instantsearch", "aa", "AlgoliaAnalytics"],
  },
  {
    id: "constructor",
    name: "Constructor.io",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://constructor.io",
    url: [/cnstrc\.com/i, /constructor\.io/i],
    html: [/constructorio/i, /cnstrc/i, /data-cnstrc/i],
    global: ["ConstructorioClient", "_constructorio", "cnstrc"],
  },
  {
    id: "bloomreach",
    name: "Bloomreach Discovery",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://www.bloomreach.com",
    url: [/bloomreach\.com/i, /brsrvr\.com/i, /\.brcdn\.com/i, /dxpapi/i, /pathways\.brsrvr/i],
    html: [/bloomreach/i, /\bbrsm\b/i, /br_data/i],
    global: ["br_data", "BrTrk", "exponea"],
  },
  {
    id: "coveo",
    name: "Coveo",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://www.coveo.com",
    url: [/coveo\.com/i, /cloud\.coveo/i, /static\.cloud\.coveo/i],
    html: [/coveo/i, /CoveoSearchInterface/i],
    global: ["Coveo", "coveoua"],
  },
  {
    id: "searchspring",
    name: "Searchspring",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://searchspring.com",
    url: [/searchspring\.net/i, /searchspring\.io/i, /searchspring\.com/i],
    html: [/searchspring/i],
    global: ["SearchSpring", "searchspring"],
  },
  {
    id: "klevu",
    name: "Klevu",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://www.klevu.com",
    url: [/klevu\.com/i, /js\.klevu/i, /\.ksearchnet\.com/i],
    html: [/klevu/i, /klevuConfig/i],
    global: ["klevu", "Klevu", "klevuConfig"],
  },
  {
    id: "unbxd",
    name: "Unbxd (Netcore)",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://unbxd.com",
    url: [/unbxd\.com/i, /libraries\.unbxdapi/i, /search\.unbxd/i],
    html: [/unbxd/i],
    global: ["Unbxd", "UnbxdAnalyticsConf"],
  },
  {
    id: "doofinder",
    name: "Doofinder",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://www.doofinder.com",
    url: [/doofinder\.com/i, /cdn\.doofinder/i],
    html: [/doofinder/i, /dfClassicLayers/i],
    global: ["doofinder", "dfClassicLayers", "doofinderLoader"],
  },
  {
    id: "findologic",
    name: "Findologic",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://www.findologic.com",
    url: [/findologic\.com/i, /cdn\.findologic/i],
    html: [/findologic/i, /flAjax/i],
    global: ["Findologic"],
  },
  {
    id: "factfinder",
    name: "FACT-Finder",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://www.fact-finder.com",
    url: [/fact-finder\.com/i, /\.fact-finder\./i, /factfinder/i],
    html: [/fact-finder/i, /factfinder/i],
  },
  {
    id: "hawksearch",
    name: "Hawksearch (Bridgeline)",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://www.hawksearch.com",
    url: [/hawksearch\.(com|net|io)/i, /\.hawksearch\./i],
    html: [/hawksearch/i],
    global: ["HawkSearch", "hawksearch"],
  },
  {
    id: "loop54",
    name: "Loop54 (Quickly/eSales)",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://www.loop54.com",
    url: [/loop54\.(com|io)/i, /\.54proxy\./i],
    html: [/loop54/i, /lib54/i],
    global: ["Loop54"],
  },
  {
    id: "empathy",
    name: "Empathy.co",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://empathy.co",
    url: [/empathy\.co/i, /empathybroker/i, /\.x\.empathy/i],
    html: [/empathy/i, /x-components/i],
  },
  {
    id: "lucidworks",
    name: "Lucidworks (Fusion)",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://lucidworks.com",
    url: [/lucidworks\.com/i, /\.lucidworks\./i],
    html: [/lucidworks/i, /fusion/i],
  },
  {
    id: "elastic",
    name: "Elastic / Elasticsearch",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://www.elastic.co",
    url: [/\.found\.io/i, /\.es\.io/i, /elastic\.co/i, /elasticsearch/i],
    html: [/elasticsearch/i, /elastic-search-ui/i],
  },
  {
    id: "swiftype",
    name: "Swiftype (Elastic Site Search)",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://www.elastic.co/products/site-search",
    url: [/swiftype\.com/i, /swiftypecdn/i, /s\.swiftypecdn/i],
    html: [/swiftype/i, /SwiftypeObject/i],
    global: ["Swiftype", "_st"],
  },
  {
    id: "yext",
    name: "Yext Search",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://www.yext.com",
    url: [/yext\.com/i, /yextpages/i, /cdn\.yextapis/i, /\.yextapis\.com/i],
    html: [/yext/i, /AnswersExperience/i],
    global: ["AnswersExperience", "Yext"],
  },
  {
    id: "typesense",
    name: "Typesense",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://typesense.org",
    url: [/typesense\.(org|net)/i, /\.a1\.typesense/i],
    html: [/typesense/i],
    global: ["Typesense", "typesenseInstantsearchAdapter"],
  },
  {
    id: "meilisearch",
    name: "Meilisearch",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://www.meilisearch.com",
    url: [/meilisearch\.com/i, /\.meilisearch\./i],
    html: [/meilisearch/i],
    global: ["MeiliSearch", "meilisearch"],
  },
  {
    id: "attraqt",
    name: "Attraqt (Fredhopper / XO)",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://www.attraqt.com",
    url: [/attraqt\.com/i, /fredhopper/i, /\.attraqt\./i, /xo-cdn/i],
    html: [/attraqt/i, /fredhopper/i],
  },
  {
    id: "sli",
    name: "SLI Systems (now part of EPAM)",
    category: CAT.SEARCH,
    competitor: true,
    website: "https://www.sli-systems.com",
    url: [/sli-spark\.com/i, /sli-systems/i, /resultspage\.com/i],
    html: [/sli_/i, /sli-systems/i],
  },

  // ---------------------------------------------------------------------------
  // Personalization / recommendations
  // ---------------------------------------------------------------------------
  {
    id: "nosto",
    name: "Nosto",
    category: CAT.PERSONALIZATION,
    competitor: true,
    website: "https://www.nosto.com",
    url: [/nosto\.com/i, /connect\.nosto/i],
    html: [/nosto/i, /nostojs/i],
    global: ["nostojs", "Nosto"],
  },
  {
    id: "dynamicyield",
    name: "Dynamic Yield",
    category: CAT.PERSONALIZATION,
    competitor: true,
    website: "https://www.dynamicyield.com",
    url: [/dynamicyield\.com/i, /\.dynamicyield\./i, /cdn\.dynamicyield/i],
    html: [/dynamicyield/i, /dyApi/i, /DYO\b/],
    global: ["DY", "DYO", "dyApi"],
  },
  {
    id: "monetate",
    name: "Monetate (Kibo)",
    category: CAT.PERSONALIZATION,
    competitor: true,
    website: "https://monetate.com",
    url: [/monetate\.net/i, /monetate\.com/i],
    html: [/monetate/i],
    global: ["monetate", "monetateT"],
  },
  {
    id: "richrelevance",
    name: "RichRelevance (Algonomy)",
    category: CAT.PERSONALIZATION,
    competitor: true,
    website: "https://algonomy.com",
    url: [/richrelevance\.com/i, /algonomy\.com/i, /\.rich-rel\./i],
    html: [/richrelevance/i, /algonomy/i],
    global: ["RR", "r3"],
  },
  {
    id: "certona",
    name: "Certona (Kibo)",
    category: CAT.PERSONALIZATION,
    competitor: true,
    website: "https://kibocommerce.com",
    url: [/certona\.(com|net)/i, /resx\.certona/i],
    html: [/certona/i, /resonance/i],
    global: ["certona"],
  },
  {
    id: "reflektion",
    name: "Reflektion (Algonomy)",
    category: CAT.PERSONALIZATION,
    competitor: true,
    website: "https://algonomy.com",
    url: [/reflektion\.com/i, /\.rfksrv\.com/i],
    html: [/reflektion/i, /rfk/i],
    global: ["rfk", "Reflektion"],
  },
  {
    id: "recombee",
    name: "Recombee",
    category: CAT.PERSONALIZATION,
    competitor: true,
    website: "https://www.recombee.com",
    url: [/recombee\.com/i, /\.recombee\./i],
    html: [/recombee/i],
    global: ["recombee"],
  },
  {
    id: "bunting",
    name: "Bunting",
    category: CAT.PERSONALIZATION,
    competitor: true,
    website: "https://www.bunting.com",
    url: [/bunting\.com/i, /\.bunting\./i],
    html: [/bunting/i],
  },

  // ---------------------------------------------------------------------------
  // Merchandising / experience / CDP often bundled with discovery suites
  // ---------------------------------------------------------------------------
  {
    id: "exponea",
    name: "Bloomreach Engagement (Exponea)",
    category: CAT.MERCH,
    competitor: true,
    website: "https://www.bloomreach.com",
    url: [/exponea\.com/i, /\.exponea\./i, /api\.exponea/i],
    html: [/exponea/i],
    global: ["exponea"],
  },
  {
    id: "fresh-relevance",
    name: "Fresh Relevance",
    category: CAT.MERCH,
    competitor: true,
    website: "https://www.freshrelevance.com",
    url: [/freshrelevance\.com/i, /\.bm23\.com/i, /\.sailthru/i],
    html: [/freshrelevance/i],
  },

  // ---------------------------------------------------------------------------
  // Commerce platforms (useful context for who the prospect is)
  // ---------------------------------------------------------------------------
  {
    id: "shopify",
    name: "Shopify",
    category: CAT.PLATFORM,
    website: "https://www.shopify.com",
    url: [/cdn\.shopify\.com/i, /shopifycloud/i, /\.myshopify\.com/i],
    html: [/Shopify\.theme/i, /shopify/i, /cdn\.shopify/i],
    global: ["Shopify"],
  },
  {
    id: "magento",
    name: "Magento / Adobe Commerce",
    category: CAT.PLATFORM,
    website: "https://business.adobe.com/products/magento",
    url: [/\/static\/version\d+\/frontend\//i, /mage\//i],
    html: [/Magento_/i, /mage\/cookies/i, /data-mage-init/i],
    global: ["Magento"],
  },
  {
    id: "salesforce-cc",
    name: "Salesforce Commerce Cloud (Demandware)",
    category: CAT.PLATFORM,
    website: "https://www.salesforce.com/products/commerce-cloud/",
    url: [/demandware\.(net|static)/i, /\.demandware\./i],
    html: [/demandware/i, /dwfrm/i, /Sites-/i],
  },
  {
    id: "bigcommerce",
    name: "BigCommerce",
    category: CAT.PLATFORM,
    website: "https://www.bigcommerce.com",
    url: [/bigcommerce\.com/i, /cdn\d+\.bigcommerce/i],
    html: [/bigcommerce/i, /stencil/i],
  },
  {
    id: "commercetools",
    name: "commercetools",
    category: CAT.PLATFORM,
    website: "https://commercetools.com",
    url: [/commercetools\.com/i, /\.ct\.eu/i],
    html: [/commercetools/i],
  },
  {
    id: "sfra-react",
    name: "SAP Commerce (Hybris)",
    category: CAT.PLATFORM,
    website: "https://www.sap.com/products/crm/e-commerce-platforms.html",
    url: [/hybris/i],
    html: [/hybris/i, /\/yacceleratorstorefront\//i],
  },

  // ---------------------------------------------------------------------------
  // A couple of analytics tags (handy context, not the focus)
  // ---------------------------------------------------------------------------
  {
    id: "ga4",
    name: "Google Analytics / GTM",
    category: CAT.ANALYTICS,
    website: "https://marketingplatform.google.com/about/analytics/",
    url: [/googletagmanager\.com/i, /google-analytics\.com/i, /analytics\.google\.com/i],
    global: ["gtag", "dataLayer", "ga"],
  },
  {
    id: "segment",
    name: "Segment",
    category: CAT.ANALYTICS,
    website: "https://segment.com",
    url: [/cdn\.segment\.com/i, /api\.segment\.io/i],
    global: ["analytics"],
  },
];

module.exports = { SIGNATURES, CAT };
